apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-producer
  namespace: default
spec:
  template:
    spec:
      containers:
      - name: producer
        image: pavan050/kafka-producer:v1
      restartPolicy: Never
  backoffLimit: 2

