apiVersion: v1
data:
  otel-collector-config.yaml: |+
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlphttp/kloudmate:
        endpoint: https://otlp.kloudmate.com
        headers:
          Authorization: "Bearer sk_lVT15IxV4GCUkYxHhVS3zbYX"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/kloudmate]

kind: ConfigMap
metadata:
  creationTimestamp: null
  name: otel-collector-config
  namespace: monitoring
