apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-config
  namespace: default
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:

    processors:
      batch:

    exporters:
      otlphttp/kloudmate:
        endpoint: https://otlp.kloudmate.com
        headers:
          Authorization: "Bearer sk_m99L18ibJKWZvJffRH5RD2LB"

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlphttp/kloudmate]

